name: molecule
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - molecule[docker,lint]
  - ansible
  - ansible-lint
  - cerberus
  - click
  - click-completion
  - click-help-colors
  - colorama
  - cookiecutter >=1.6.0,!=1.7.1
  - jinja2 >=2.10.1
  - paramiko >= 2.5.0,<3
  - pexpect >=4.6.0,<5
  - pluggy >=0.7.1,<1.0
  - python-gilt >=1.2.1,<2
  - pyyaml >=5.1,<6
  - sh >=1.12.1,<1.13
  - tabulate >=0.8.4
  - tree-format >=0.1.2
  - yamllint >=1.15.0,<2
  - docker-py >=2.0.0
  - flake8 >=3.6.0
  - pre-commit >=1.21.0
