---

- name: ensure defaults were not modified
  assert:
    that:
      - "opt_conda_prefix == '/opt/conda'"
      - "opt_conda == opt_conda_prefix + '/condabin/conda'"

- name: install the conda package manager
  include_tasks: "{{ ansible_facts['os_family'] }}.yaml"

- name: configure conda
  include_tasks: config.yaml
