---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: ubuntu-latest
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
